version: '3'
services:

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && apt-get install mysql-server -y && service mysql stop && service mysql start && rake db:create && rake db:drop db:create db:schema:load && bundle exec rails s -p 3307 -b '0.0.0.0' "
    volumes:
      - .:/myapp
    ports:
      - "3307:3307"
    